##db = DAL("postgres://reingart:clave@localhost:5432/terciario", pool_size=10)

migrate = True

db.define_table('alumnos',
    Field('alumnoid', type='id'),
    Field('nombre', type='string', length=200),
    Field('codigo', type='string', length=50),
    Field('dni', type='integer'),
    Field('sexo', type='string', length=1),
    Field('fechanacimiento', type='date'),
    Field('lugarnacimiento', type='string', length=250),
    Field('estadocivil', type='string', length=50),
    Field('nacionalidad', type='string', length=50),
    Field('direccion', type='string', length=200),
    Field('localidad', type='string', length=50),
    Field('cp', type='string', length=7),
    Field('telefonos', type='string', length=250),
    Field('email1', type='string', length=100),
    Field('email2', type='string', length=100),
    Field('ingreso', type='date'),
    Field('egreso', type='date'),
    Field('emergencias', type='string', length=200),
    Field('nivelestudio', type='string', length=1),
    Field('estudioscompletos', type='boolean', default=False),
    Field('estudioscursadosen', type='string', length=50),
    Field('titulo', type='string', length=200),
    Field('faltasolicitudinscripcion', type='boolean', default=False),
    Field('faltareglamentoreservavacante', type='boolean', default=False),
    Field('faltafotos', type='boolean', default=False),
    Field('faltaaptofisico', type='boolean', default=False),
    Field('faltavencimientoapto', type='boolean', default=False),
    Field('faltadni', type='boolean', default=False),
    Field('faltapartidanacimiento', type='boolean', default=False),
    Field('faltatitulosecundariolegalizado', type='boolean', default=False),
    Field('faltaanaliticopase', type='boolean', default=False),
    Field('faltaconstaciatitulotramite', type='boolean', default=False),
    Field('faltavencimientoconstanciatitulotramite', type='boolean', default=False),
    Field('faltaconstaciapasetramite', type='boolean', default=False),
    Field('faltavencimientoconstanciapasetramite', type='boolean', default=False),
    Field('faltaconstaciamateriasaprobadas', type='boolean', default=False),
    Field('faltavencimientoconstanciamateriasaprobadas', type='boolean', default=False),
    Field('faltaautorizacionretiroalumno', type='boolean', default=False),
    Field('faltafichamedica', type='boolean', default=False),
    Field('faltavacunas', type='boolean', default=False),
    Field('faltacertificadobucodental', type='boolean', default=False),
    Field('faltainformenivelinicial', type='boolean', default=False),
    Field('faltaboletin', type='boolean', default=False),
    Field('folmat', type='string', length=50),
    Field('baja', type='date'),
    migrate=migrate)

db.define_table('asignaturas',
    Field('asignaturaid', type='id'),
    Field('nombre', type='string', length=200),
    Field('materiaid', db.materias.id),
    Field('cursoid', db.cursos.id),
    Field('carreraid', db.carreras.id),
    Field('planestudioid', db.planesestudio.id),
    Field('orden', type='integer', default=0),
    Field('horas', type='integer'),
    Field('teorica', type='boolean', default=False),
    Field('practica', type='boolean', default=False),
    Field('optativa', type='boolean', default=False),
    Field('faltas1r', type='integer', default=0),
    Field('faltaslibre', type='integer', default=0),
    Field('faltasrecursa', type='integer', default=0),
    Field('cicloid', db.ciclos.id),
    migrate=migrate)

db.define_table('calendarios',
    Field('calendarioid', type='id'),
    Field('fecha', type='date'),
    Field('feriado', type='boolean', default=False),
    Field('mensaje', type='string', length=50),
    migrate=migrate)

db.define_table('calificaciones',
    Field('calificacionid', type='id'),
    Field('calificacion', type='string', length=50),
    Field('codigo', type='string', length=1),
    Field('condicion', type='string', length=50),
    Field('ayuda', type='text'),
    Field('equivalencia', type='boolean', default=False),
    Field('previa', type='boolean', default=False),
    migrate=migrate)

db.define_table('cargos',
    Field('cargoid', type='id'),
    Field('cargo', type='string', length=50),
    migrate=migrate)

db.define_table('carreras',
    Field('carreraid', type='id'),
    Field('nombre', type='string', length=250),
    migrate=migrate)

db.define_table('catedras',
    Field('catedraid', type='id'),
    Field('nombre', type='string', length=150),
    Field('informe', type='string', length=50),
    Field('boletin', type='string', length=50),
    Field('analitico', type='string', length=50),
    Field('espacio', type='string', length=1),
    Field('abr', type='string', length=50),#abreviaturas
    Field('calificacion', type='string', length=50),
    Field('horas', type='integer', default=0),
    Field('minutos', type='integer', default=0),
    Field('nivelid', db.niveles.id),
    Field('codigo', type='string', length=5),
    migrate=migrate)

db.define_table('ciclos',
    Field('cicloid', type='id'),
    Field('nombre', type='string', length=50),
    Field('anio', type='integer', default=0),
    Field('detalle', type='string', length=100),
    Field('desde', type='date'),
    Field('hasta', type='date'),
    migrate=migrate)

db.define_table('comisiones',
    Field('comisionid', type='id'),
    Field('nombre', type='string', length=200),
    Field('divisionid', db.divisiones.id),
    Field('periodoid', db.periodos.id),
    Field('materiaid', db.materias.id),
    Field('personalid', db.personal.id),
    Field('faltas1r', type='double'),
    Field('faltas2r', type='double'),
    Field('faltaslibre', type='double'),
    Field('faltasrecursa', type='double'),
    migrate=migrate)

db.define_table('correlativas',
    Field('correlativaid', type='id'),
    Field('materiaid1', db.materias.id),
    Field('materiaid2', db.materias.id),
    Field('planestudioid', db.planesestudio.id),
    migrate=migrate)

db.define_table('cursos',
    Field('cursoid', type='id'),
    Field('nombre', type='string', length=50),
    Field('codigo', type='string', length=3),
    Field('nivel', type='integer', default=0),
    Field('anio', type='string', length=50),
    Field('seccion', type='string', length=2),
    Field('division', type='string', length=3),
    Field('orden', type='integer', default=0),
    migrate=migrate)

db.define_table('divisiones',
    Field('divisionid', type='id'),
    Field('division', type='string', length=50),
    Field('codigo', type='string', length=5),
    Field('cursoid', db.cursos.id),
    Field('cicloid', db.ciclos.id),
    Field('numero', type='string', length=1),
    Field('letra', type='string', length=1),
    Field('turno', type='string', length=1),
    Field('anio', type='integer'),
    migrate=migrate)

db.define_table('examenes',
    Field('examenid', type='id'),
    Field('materiaid', db.materias.id),
    Field('periodoid', db.periodos.id),
    Field('llamado', type='string', length=1),
    Field('turno', type='string', length=1),
    Field('fecha', type='date'),
    Field('hora', type='date'),
    Field('personalid1', db.personal.id),
    Field('personalid2', db.personal.id),
    Field('personalid3', db.personal.id),
    Field('personalid4', db.personal.id),
    migrate=migrate)

db.define_table('faltas',
    Field('faltaid', type='id'),
    Field('alumnoid', db.alumnos.id),
    Field('comisionid', db.comisiones.id),
    Field('inasistenciaid', db.inasistencias.id),
    Field('fecha', type='date'),
    Field('cantidad', type='double', default=0),
    Field('justificado', type='boolean', default=False),
    Field('detalle', type='string', length=50),
    Field('web', type='boolean', default=False),
    migrate=migrate)

db.define_table('horarios',
    Field('horarioid', type='id'),
    Field('horaid', db.horas.id),
    Field('dia', type='string', length=1),
    Field('materiaid', db.materias.id),
    Field('detalle', type='string', length=25),
    migrate=migrate)

db.define_table('horas',
    Field('horaid', type='id'),
    Field('hora', type='string', length=25),
    Field('desde', type='date'),
    Field('hasta', type='date'),
    Field('nivelid', db.niveles.id),
    migrate=migrate)

db.define_table('inasistencias',
    Field('inasistenciaid', type='id'),
    Field('inasistencia', type='string', length=50),
    Field('tarde', type='boolean', default=False),
    migrate=migrate)

db.define_table('inscripcionescomision',
    Field('inscripcionid', type='id'),
    Field('alumnoid', db.alumnos.id),
    Field('comisionid', db.comisiones.id),
    Field('alta', type='date'),
    Field('baja', type='date'),
    Field('condicion', type='string', length=1),
    migrate=migrate)

db.define_table('inscripcionesdivision',
    Field('inscripcionid', type='id'),
    Field('alumnoid', db.alumnos.id),
    Field('divisionid', db.divisiones.id),
    Field('alta', type='date'),
    Field('baja', type='date'),
    Field('condicion', type='string', length=1),
    migrate=migrate)

db.define_table('inscripcionesexamen',
    Field('inscripcionid', type='id'),
    Field('alumnoid', db.alumnos.id),
    Field('examenid', db.examenes.id),
    Field('condicion', type='string', length=1),
    Field('alta', type='date'),
    Field('baja', type='date'),
    Field('confirmar', type='boolean', default=False),
    Field('valido', type='boolean', default=False),
    migrate=migrate)

db.define_table('materias',
    Field('materiaid', type='id'),
    Field('nombre', type='string', length=100),
    Field('resumen', type='string', length=50),
    Field('cursoid', db.cursos.id),
    Field('catedraid', db.catedras.id),
    Field('codigo', type='string', length=5),
    Field('orden', type='integer', default=0),
    Field('optativa', type='boolean', default=False),
    Field('analitico', type='string', length=250),
    Field('requerida', type='boolean', default=False),
    migrate=migrate)

db.define_table('niveles',
    Field('nivelid', type='id'),
    Field('nivel', type='string', length=50),
    Field('ciclo', type='integer', default=0),
    Field('tipo', type='integer', default=0),
    Field('personalid', db.personal.id),
    migrate=migrate)

db.define_table('notas',
    Field('notaid', type='id'),
    Field('alumnoid', db.alumnos.id),
    Field('materiaid', db.materias.id),
    Field('periodoid',db.periodos.id),
    Field('calificacionid',db.calificaciones.id ),
    Field('nota', type='double', default=0),
    Field('descripcion', type='string', length=50),
    Field('establecimiento', type='string', length=50),
    Field('observaciones', type='text'),
    Field('fecha', type='date'),
    Field('libro', type='string', length=5),
    Field('folio', type='integer'),
    Field('alta', type='date', default=request.now),
    Field('web', type='boolean', default=False),
    Field('turno', type='string', length=1),
    migrate=migrate)

db.define_table('periodos',
    Field('periodoid', type='id'),
    Field('descripcion', type='string', length=50),
    Field('nivelid', db.niveles.id),
    Field('cicloid', db.ciclos.id),
    Field('mes', type='integer', default=0),
    Field('anio', type='integer', default=0),
    Field('trimestre', type='integer', default=0),
    Field('condicion', type='string', length=50),
    Field('cuatrimestre', type='integer', default=0),
    Field('semestre', type='integer', default=0),
    Field('orden', type='integer', default=0),
    Field('codigo', type='string', length=1),
    Field('inicio', type='date'),
    Field('cierre', type='date'),
    Field('tipo', type='integer', default=0),
    Field('dias', type='integer', default=0),
    Field('secuencia', type='integer'),
    Field('notaminima', type='double'),
    migrate=migrate)

db.define_table('personal',
    Field('personalid', type='id'),
    Field('nombre', type='string', length=50),
    Field('dni', type='integer', length=50),
    Field('nacimiento', type='date'),
    Field('domicilio', type='string', length=50),
    Field('localidad', type='string', length=50),
    Field('cp', type='string', length=50),
    Field('provincia', type='string', length=50),
    Field('telefono', type='string', length=50),
    Field('titulos', type='string', length=255),
    Field('otorgadospor', type='string', length=255),
    Field('fechaotorgamiento', type='string', length=50),
    Field('apto', type='string', length=50),
    Field('nombramiento', type='date'),
    Field('cuil', type='string', length=50),
    Field('cargoid', db.cargos.id),
    Field('seccionid', db.secciones.id),
    migrate=migrate)

db.define_table('planesestudio',
    Field('planestudioid', type='id'),
    Field('planestudio', type='string', length=50),
    Field('aprobadopor', type='string', length=250),
    Field('carreraid', db.carreras.id),
    Field('desde', type='date'),
    Field('hasta', type='date'),
    migrate=migrate)

db.define_table('profesores',
    Field('profesorid', type='id'),
    Field('personalid', db.personal.id),
    Field('comisionid', db.comisiones.id),
    Field('cargoid', db.cargos.id),
    Field('revistaid', db.revistas.id),
    Field('licencia', type='boolean', default=False),
    Field('detalle', type='string', length=50),
    Field('ref', type='string', length=1),
    migrate=migrate)

db.define_table('revistas',
    Field('revistaid', type='id'),
    Field('nombre', type='string', length=50),
    migrate=migrate)

db.define_table('sanciones',
    Field('sancionid', type='id'),
    Field('alumnoid', db.alumnos.id),
    Field('fecha', type='date'),
    Field('cantidad', type='double', default=0),
    Field('tipo', type='string', length=1),
    Field('detalle', type='text'),
    Field('parte', type='integer', default=0),
    migrate=migrate)

db.define_table('secciones',
    Field('seccionid', type='id'),
    Field('seccion', type='string', length=50),
    migrate=migrate)

db.define_table('situaciones',
    Field('situacionid', type='id'),
    Field('detalle', type='string', length=30),
    migrate=migrate)

db.define_table('titulos',
    Field('tituloid', type='id'),
    Field('titulo', type='string', length=250),
    Field('planestudioid', db.planesestudio.id),
    Field('carreraid', db.carreras.id),
    Field('cursoid', db.cursos.id),
    migrate=migrate)
